### ISSUE TITLE
isObject([]) should return true

### ISSUE THREAD

**Issue by ruanmartinelli** [daltonmenezes/what-type-is#1]
Arrays in JavaScript do have some special properties like `.length` and `.push()` but according to the [spec](https://www.ecma-international.org/ecma-262/5.1/#sec-15.4) they are still considered objects. 

You can confirm this behavior using the `typeof` operator:

```js
typeof [1, 2, 3]
// => 'object'
```
This means that the `isObject()` function should return `true` for Arrays instead of `false`.

**Comment by daltonmenezes** [comment]
When you need to know if an input or output value is an Object, Array, etc. to make a strategy in the logic of your project, the values returned by ```typeof``` do not help. If you use ```Object.prototype.toString.call``` the return will be ```'Object Array'```.

When you are using a **'is'** type lib, what do you really want to know? If this is an array or an object? Almost everything will be an object in javascript and I believe use that way does not help in checking to put together on a project strategy.

**Comment by ruanmartinelli** [comment]
I totally get your point.

What I'd suggest is to at least change the function signature so it clearly states what it does.

As an example, [lodash](https://lodash.com/docs/) has the `_.isObject` and `_.isPlainObject` methods available. The first one validates from the spec and the second behaves similar to what you are trying to achieve.

**Comment by daltonmenezes** [comment]
Great suggestion. I'll do it like lodash as you showed. Thanks @ruanmartinelli
